
user  nginx;
worker_processes  auto;

error_log  /egova/log/nginx/error.log warn;


events {
    #accept_mutex on;
    #multi_accept on;
    #use epoll;
    worker_connections  1048576;
}


http {
    include       /usr/local/openresty/nginx/conf/mime.types;
    default_type  application/octet-stream;

    proxy_hide_header X-Powered-By;
    proxy_hide_header Server;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent $upstream_response_time $request_time $upstream_addr';
    log_format  detail  '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent $upstream_response_time $request_time $upstream_addr $request_body $http_cookie';
    
    map $status $mainflag {
           ~^[123]  1;
           default 0;
    }
    map $status $detailflag {
       ~^[45]  1;
       default 0;
    }
    access_log  /egova/log/nginx/access.log  main if=$mainflag;
    access_log  /egova/log/nginx/access.log  detail if=$detailflag;
    #access_log off;

    sendfile        on;
    tcp_nopush     on;
    server_tokens off;
    keepalive_timeout  65;

    gzip  on;
    gzip_min_length 1024;
    gzip_buffers 32 4k;
    gzip_comp_level 1;
    gzip_types text/plain application/javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png image/vnd.microsoft.icon image/x-icon application/json image/svg+xml text/html font/ttf font/woff2 application/font-woff2 application/x-font-ttf application/x-font-opentype;
    gzip_vary off;
    gzip_disable "MSIE [1-6]\.";

    client_max_body_size 500m;

    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/conf.d/*.upstream;
    include /etc/nginx/conf.d/*.lua;
}

stream {
    include /etc/nginx/conf.d/*.tcp;
}
