---
# handlers for crond
- name: restart crond
  service: name=cron state=restarted enabled=yes
  when: ansible_distribution in ['openEuler', 'kylin_V10_arm','Ubuntu','kylin_x86']

- name: restart crond
  command: service crond restart
  when: ansible_distribution == 'CentOS'