- name: check if xtrabackup-cron exists
  shell: "cat /etc/crontab |grep cron_db_backup_xtrabackup |wc -l"
  register: file_count
  ignore_errors: yes


- name: check if xtrabackup exists
  shell: "dpkg -l | grep percona-xtrabackup-80"
  register: check_xtrabackup_output_apt
  ignore_errors: yes
  when: ansible_pkg_mgr ==  'apt'

- name: check if xtrabackup exists
  shell: "rpm -q percona-xtrabackup-80"
  register: check_xtrabackup_output_other
  ignore_errors: yes
  when: ansible_pkg_mgr in ['dnf', 'yum']


# 安装安装mysql备份工具
- block:
    - name: 卸载procps-ng-help
      package:
        name: procps-ng-help
        state: 'absent'
      when:  ansible_distribution == 'kylin_x86'

    - name: 安装mysql备份工具
      package:
        name: "{{ mysql_percona_xtrabackup_packages[ansible_distribution] }}"
        state: 'present'
        update_cache: yes
  when:  ansible_distribution in ['openEuler', 'kylin_arm','Ubuntu','CentOS','kylin_x86','UOS','uos_x86','uos_arm','anolis_x86','anolis_arm']


- block:
    - name: 创建mysqlbackup目录
      file:
        path: "{{ item }}"
        state: directory
        mode: '0770'
      with_items:
        - "{{ backup_path }}"
        - "{{ tools_path }}"

    - name: 拷贝cron_db_backup_xtrabackup.sh
      copy:
        src=cron_db_backup_xtrabackup.sh dest={{ tools_path }}/cron_db_backup_xtrabackup.sh mode='0755'

    - name: 数据库备份定时任务追加到crontab
      blockinfile:
        path: /etc/crontab
        state: present
        create: yes
        marker: '# {mark} Ansible generated by oninstall_v2 xtrabackup'
        block: |
         00 02 * * 0 root {{ tools_path }}/cron_db_backup_xtrabackup.sh -full
         00 02 * * 1-6 root {{ tools_path }}/cron_db_backup_xtrabackup.sh -incr
      notify:
        - restart crond
  when: file_count.stdout == "0"