# ansible hosts文件

# 所有ansible受控节点，此处需保存节点host和ip的对应关系
all:
  hosts:
    node1:
      ansible_ssh_host: 192.168.101.204
    node2:
      ansible_ssh_host: 192.168.101.205
    node3:
      ansible_ssh_host: 192.168.101.206
    node4:
      ansible_ssh_host: 192.168.101.207

  children:
    # mysql服务器，部署完mysql后记录一条，便于后续批量更新等操作。
    mysql:
      hosts:

    # redis服务器
    redis:
      hosts:

    # minio服务器
    minio:
      hosts:


    # nginx服务器
    nginx:
      hosts:

    # linglong, 一个节点多个linglong，如何滚动更新
    linglong:
      hosts:

    wukong:
      hosts:

    dex:
      hosts:

    eurbanpro:
      hosts:
