# ansible hosts文件， 此hosts文件仅供ansible使用，保存所有ansible受控节点信息。
# 主机名是自动生成，不代表实际的主机名称。
all:
  hosts:

  children:
    # mysql服务器，部署完mysql后记录一条，便于后续批量更新等操作。
    mysql:
      hosts:
    # redis服务器
    redis:
      hosts:
    # minio服务器
    minio:
      hosts:
    # nginx服务器
    nginx:
      hosts:
    # linglong, 一个节点多个linglong，如何滚动更新
    linglong:
      hosts:
    wukong:
      hosts:
    dex:
      hosts:
    httpfileservice:
      hosts:
    gisserver:
      hosts:
    zookeeper:
      hosts:
    kafka:
      hosts:
    usercenter:
      hosts:
    xuanzang:
      hosts:
    video:
      hosts:
    eurbanpro:
      hosts: