# 明镜执法微服务分布式部署配置
# 服务器配置
ip_db_biz:
  name: 业务数据库
  sub_flag: 1
  need_flag: 1
  biz_flag: 0
  tiny_flag: 1
  choice_index: 1
  deploy_status_flag: 0
  modules:
    - type: mysql
      name: 业务库
      sub_type: biz
    - type: cetus
      name: 业务库代理
      sub_type: biz
  hosts:
    master:
    slave:

ip_web_redis:
  name: 业务REDIS服务器
  sub_flag: 1
  need_flag: 1
  biz_flag: 0
  tiny_flag: 1
  choice_index: 3
  deploy_status_flag: 0
  modules:
    - type: redis
      name: redis内存数据库
      sub_type: redis
  hosts:
    master:
    slave:

ip_web_nacos:
  name: NACOS服务器
  sub_flag: 0
  need_flag: 1
  biz_flag: 0
  tiny_flag: 1
  choice_index: 4
  deploy_status_flag: 0
  modules:
    - type: nacos
      name: nacos注册中心
      sub_type: nacos
  hosts:
    master:
    slave:

ip_tool_postgis:
  name: PG数据库服务器
  sub_flag: 1
  need_flag: 1
  biz_flag: 0
  tiny_flag: 1
  choice_index: 6
  deploy_status_flag: 0
  modules:
    - type: postgresql
      name: PG数据库
      sub_type: pg
  hosts:
    master:
    slave:

ip_web_mjing:
  name: 明镜执法服务器
  sub_flag: 1
  need_flag: 1
  biz_flag: 0
  tiny_flag: 1
  choice_index: 7
  deploy_status_flag: 0
  modules:
    - type: microservice
      name: 明镜执法微服务
      sub_type: mjing
  hosts:
    master:
    slave: 

ip_web_media:
  name: 多媒体服务器
  sub_flag: 0
  need_flag: 1
  biz_flag: 0
  tiny_flag: 1
  choice_index: 8
  deploy_status_flag: 0
  modules:
    - type: microservice
      name: http共享目录服务
      sub_type: httpfileservice
    - type: minio
      name: minio
      sub_type: minio
  hosts:
    master:
    slave:

ip_web_job:
  name: ZOOKEEPER服务器
  sub_flag: 0
  need_flag: 1
  biz_flag: 0
  tiny_flag: 1
  choice_index: 9
  deploy_status_flag: 0
  modules:
    - type: zookeeper
      name: zookeeper
      sub_type: zookeeper
  hosts:
    master:
    slave:

ip_web_usercenter:
  name: 用户中心服务器
  sub_flag: 1
  need_flag: 1
  biz_flag: 0
  tiny_flag: 1
  choice_index: x2
  deploy_status_flag: 0
  modules:
    - type: microservice
      name: 用户中心2.0微服务
      sub_type: usercenter
  hosts:
    master:
    slave:

ip_web_linglong:
  name: 灵珑服务器
  sub_flag: 1
  need_flag: 1
  biz_flag: 0
  tiny_flag: 1
  choice_index: x3
  deploy_status_flag: 0
  modules:
    - type: microservice
      name: 灵珑微服务
      sub_type: linglong
  hosts:
    master:
    slave:

ip_web_xuanzang:
  name: 玄藏服务器
  sub_flag: 0
  need_flag: 1
  biz_flag: 0
  tiny_flag: 1
  choice_index: x4
  deploy_status_flag: 0
  modules:
    - type: microservice
      name: 玄藏微服务
      sub_type: xuanzang
  hosts:
    master:
    slave:

ip_web_evaluation:
  name: 毕升服务器
  sub_flag: 0
  need_flag: 1
  biz_flag: 0
  tiny_flag: 1
  choice_index: x5
  deploy_status_flag: 0
  modules:
    - type: microservice
      name: 毕升微服务
      sub_type: evaluation
  hosts:
    master:
    slave:

ip_web_dex:
  name: 星桥服务器
  sub_flag: 1
  need_flag: 1
  biz_flag: 0
  tiny_flag: 1
  choice_index: s
  deploy_status_flag: 0
  modules:
    - type: microservice
      name: 星桥微服务
      sub_type: dex
  hosts:
    master:
    slave:

ip_web_other:
  name: 即时通讯服务器
  sub_flag: 0
  need_flag: 1
  biz_flag: 0
  tiny_flag: 1
  choice_index: s1
  deploy_status_flag: 0
  modules:
    - type: microservice
      name: 即使通讯服务
      sub_type: IM
  hosts:
    master:
    slave:

ip_nginx_main:
  name: 出口nginx服务器
  sub_flag: 0
  need_flag: 1
  biz_flag: 0
  tiny_flag: 1
  choice_index: s2
  deploy_status_flag: 0
  modules:
    - type: nginx
      name: nginx代理
      sub_type: nginx
  hosts:
    master:
    slave:

ip_web_wukong:
  name: 悟空服务器
  sub_flag: 1
  need_flag: 1
  biz_flag: 0
  tiny_flag: 1
  choice_index: s4
  deploy_status_flag: 0
  modules:
    - type: microservice
      name: wukong微服务
      sub_type: wukong
  hosts:
    master:
    slave:

ip_web_kafka:
  name: kafka服务器
  sub_flag: 0
  need_flag: 1
  biz_flag: 0
  tiny_flag: 1
  choice_index: s5
  deploy_status_flag: 0
  modules:
    - type: kafka
      name: kafka
      sub_type: kafka
  hosts:
    master:
    slave:

ip_web_usercenter_redis:
  name: 用户中心REDIS服务器
  sub_flag: 1
  need_flag: 1
  biz_flag: 0
  tiny_flag: 1
  choice_index: s6
  deploy_status_flag: 0
  modules:
    - type: redis
      name: 用户中心内存数据库
      sub_type: usercenter_redis
  hosts:
    master:
    slave:


