---
# This playbook deploys the nginx
- name: deploy and configure the nginx
  hosts: "{{ host }}"
  gather_facts: "{{ gather_facts }}"
  remote_user: root
  # 优先级小于role/vars下定义的变量
  vars_files:
    - ./group_vars/all.yml
  roles:
    - local_repo
    - common
    - nginx
    - mysql_client
    - logrotate