# This playbook deploys the benchmarkinspection
- name: deploy and configure the inspectperformance
  hosts: "{{ host }}"
  gather_facts: "{{ gather_facts }}"
  remote_user: root
# 优先级小于role/vars下定义的变量
  vars_files:
    - ./group_vars/all.yml
#    - ./inventory/metadata.yml
  roles:
    - local_repo
    - benchmark_check


