---
# This playbook deploys the common
- name: patch the ubuntu
  hosts: "{{ host }}"
  gather_facts: "{{ gather_facts }}"
  remote_user: root
  # 优先级小于role/vars下定义的变量
  vars_files:
    - ./group_vars/all.yml
  roles:
    - common
    - mysql_client
