---
# This playbook deploys the cetus
- name: deploy and configure the cetus
  hosts: "{{ host }}"
  gather_facts: "{{ gather_facts }}"
  remote_user: root
  # 优先级小于role/vars下定义的变量
  vars_files:
    - ./group_vars/all.yml
    - ./inventory/eurbanpro_multi_server.yml
  roles:
    - local_repo
    - cetus