---
# This playbook deploys the TDengine3
- name: deploy and configure the TDengine3
  hosts: "{{ host }}"
  gather_facts: "{{ gather_facts }}"
  remote_user: root
  # 优先级小于role/vars下定义的变量
  vars_files:
    - ./group_vars/all.yml
  roles:
    - local_repo
    - common
    - docker
    - TDengine3
    - logrotate