---
- name: install mysqlclient
  hosts: "{{ host }}"
  gather_facts: "{{ gather_facts }}"
  remote_user: root
  vars_files:
    - ./group_vars/all.yml
  roles:
    #- common
    - local_repo
    - common
    - mysql_client
