---
# This playbook deploys the onlyoffice
- name: deploy and configure the onlyoffice
  hosts: "{{ host }}"
  gather_facts: "{{ gather_facts }}"
  remote_user: root
  # 优先级小于role/vars下定义的变量
  vars_files:
    - ./group_vars/all.yml
    # 注入微服务配置
    - ./inventory/template/ms_env_custom.yml
    - ./inventory/hosts.yml
  roles:
    - local_repo
    - docker
    - db_init
    - IM
    - logrotate
