# 菜单选项配置
local_repo:
  name: 安装本地源
  display: 1
  choice_index: 0
  sub_options: []

ansible_install:
  name: 安装ansible
  display: 1
  choice_index: 1
  sub_options: []

host_add:
  name: 增加服务器
  display: 1
  choice_index: 2
  sub_options: []

app_service:
  name: 应用服务部署
  display: 1
  choice_index: 3
  sub_options:
    - name: V14智信云标准（标准城管）
      category: v14
      sub_options:
        - name: 一站式部署
          type: one
          config_file: multi_server.yml
        - name: 分布式部署
          type: multi
          config_file: multi_server.yml
        - name: 轻量化部署
          type: tiny
          config_file: multi_server.yml
    - name: 麒舰平台微服务
      category: eurbanpro
      sub_options:
        - name: 分布式部署
          type: multi
          config_file: eurbanpro_multi_server.yml
    - name: 基础平台微服务
      category: basic
      sub_options: []
    - name: 一网统管业务线微服务
      category: mis
      sub_options: []
    - name: 城市运管服微服务
      category: sg
      sub_options: []
    - name: 城市生命线微服务
      category: fac
      sub_options: []
    - name: 执法业务线微服务
      category: elaw
      sub_options: []
    - name: GIS微服务
      category: gis
      sub_options: []
    - name: AI微服务
      category: ai
      sub_options: []
    - name: 明镜执法微服务
      category: mjing
      sub_options:
        - name: 分布式部署
          type: multi
          config_file: mjing_multi_server.yml

software_tool:
  name: 软件部署工具箱
  display: 1
  choice_index: 4
  sub_options: []

outlet_nginx:
  name: 配置出口nginx(微服务部署使用)
  display: 1
  choice_index: 101
  sub_options: []

benchmark_check:
  name: 基准检查
  display: 1
  choice_index: b
  sub_options: []

os_patch:
  name: 系统打补丁及优化
  display: 1
  choice_index: p
  sub_options: []

security_toolbox:
  name: 安全加固工具箱
  display: 1
  choice_index: s
  sub_options: []

modify_db:
  name: 一键切换信创数据库配置信息
  display: 1
  choice_index: m
  sub_options: []

update_script:
  name: 更新oneinstall
  display: 0
  choice_index: i
  sub_options: []
