---
# check if elasticsearch exists
- name: 检查目标目录
  stat: path={{ deploy_path }}/elasticsearch-{{ elasticsearch_version }}
  register: es_dir

- name: Fail if elasticsearch dir is not empty
  fail:
    msg: |
      检查到已经安装过elasticsearch,如需卸载请在{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}服务器上执行 mv {{ deploy_path }}/elasticsearch-{{ elasticsearch_version }} {{ deploy_path }}/elasticsearch-{{ elasticsearch_version }}_backup
  ignore_errors: yes
  when: es_dir.stat.exists == True

- block:
    - name: 准备es目录
      file: name={{ item.dir }} state=directory owner={{ ops_user }} group={{ ops_user }} mode='{{ item.mode }}'
      with_items:
        - { dir: "{{ deploy_path }}",mode: "0775" }
        - { dir: "{{ data_path }}",mode: "0775" }
    - name: 解压es
      unarchive:
        src: "{{ item.file }}"
        dest: "{{ item.dest }}"
        owner: "{{ ops_user }}"
        group: "{{ ops_user }}"
        mode: '0755'
      with_items:
        - { file: "{{ src_path }}/elasticsearch-{{ elasticsearch_version }}.tar.gz",dest: "{{ deploy_path }}" }
        - { file: "{{ src_path }}/elasticsearch-analysis-ik-{{ elasticsearch_version }}.tar.gz",dest: "{{ deploy_path }}/elasticsearch-{{ elasticsearch_version }}/plugins" }

    - name: 修正max_map_count
      blockinfile:
        path: /etc/sysctl.conf
        state: present
        create: yes
        marker: '# {mark} Ansible generated by es install'
        block: 'vm.max_map_count=262144'

    - name: sysctl
      shell: "sysctl -p "

    - name: "计算75%内存"
      shell: es_mem=`expr $(grep MemTotal /proc/meminfo |awk '{print $2}') / 1365 ` && echo ${es_mem}
      register: ES_MEM

    - set_fact:
       ES_MEM_MAX: "{{ jvm_max_memory * 1024 if (ES_MEM.stdout|int > jvm_max_memory * 1024) else ES_MEM.stdout|int }}m"

    - name: 创建软链接
      file: src={{ deploy_path }}/elasticsearch-{{ elasticsearch_version }} dest={{ deploy_path }}/elasticsearch state=link force=true

    - name: 修改配置
      template: src={{ item.filename }}.j2 dest={{ item.destpath }}/{{ item.filename }}
      with_items:
        - { filename: "jvm.options",destpath: "{{ deploy_path }}/elasticsearch-{{ elasticsearch_version }}/config/" }
        - { filename: "elasticsearch.yml",destpath: "{{ deploy_path }}/elasticsearch-{{ elasticsearch_version }}/config/" }
        - { filename: "elasticsearch.service",destpath: "/etc/systemd/system/" }

    - name: ES新增用户
      shell:
        "{{ deploy_path }}/elasticsearch/bin/elasticsearch-users useradd {{ username }} -p {{ password }} -r superuser"

    - name: daemon-reload
      systemd: daemon_reload=yes

    - name: 启动elasticsearch
      service: name=elasticsearch state=restarted enabled=yes
  when: es_dir.stat.exists == false