create database IF NOT EXISTS trace;
create database IF NOT EXISTS egovaiot;
use trace;
CREATE STABLE IF NOT EXISTS tr_log_patrol_pos (  update_time timestamp,  angle float  ,  coord_type nchar (20) ,  coordinate_b double  ,  coordinate_l double  ,  coordinate_x double  ,  coordinate_y double  ,  duty_grid_id int,  hdop float,  patrol_id int ,  patrol_state_id int  ,  pdop float ,  revised_coord_x double  ,  revised_coord_y double  ,  speed float  ,  create_time timestamp ,  vdop float ,  road_id int ,  road_name nchar(80),  client_time timestamp,  accuracy float,  card_id nchar(80) ,  in_grid_flag int,  imei nchar(80),  gps_count nchar(20)) TAGS (patrol_tag int);
CREATE STABLE IF NOT EXISTS to_vehicle_pos_history (record_time TIMESTAMP,address NCHAR (255),altitude FLOAT,angle FLOAT,coordinate_x DOUBLE,coordinate_y DOUBLE,fuel FLOAT,handle_flag INT,instant_fuel_consumption FLOAT,latitude FLOAT,longitude FLOAT,oil FLOAT,road_id INT,road_name NCHAR (255),speed FLOAT,STATUS NCHAR (255),today_course FLOAT,total_course FLOAT,upload_time TIMESTAMP,today_mileage FLOAT,total_mileage FLOAT,sealed_state TINYINT,acc_status TINYINT,lift_state TINYINT,payload_state FLOAT,payload_state_change TINYINT,on_off_group INT,working INT,fuelad INT,device_num NCHAR (255),current_water FLOAT,water FLOAT,payload FLOAT) TAGS (sim_card_num NCHAR(255));
use egovaiot;
CREATE STABLE IF NOT EXISTS iot_equip_data (time TIMESTAMP,VALUE DOUBLE,receive_time TIMESTAMP,alarm_flag TINYINT,is_noise TINYINT,value_type_id BINARY ( 10 ),detail nchar ( 1000 )) tags (equip_id BINARY ( 50 ),field_id BINARY ( 50 ),field_code BINARY ( 50 ),equip_type_id BINARY ( 50 ),region_code BINARY ( 10 ),project_id BINARY ( 10 ),manufacturer_id BINARY ( 10 ));

CREATE DATABASE IF NOT EXISTS trace_new;
CREATE STABLE IF NOT EXISTS trace_new.tr_log_patrol_pos( client_time TIMESTAMP, angle FLOAT, coord_type nchar ( 20), coordinate_b DOUBLE, coordinate_l DOUBLE, coordinate_x DOUBLE, coordinate_y DOUBLE, duty_grid_id INT, hdop FLOAT, patrol_id INT, patrol_state_id INT, pdop FLOAT, revised_coord_x DOUBLE, revised_coord_y DOUBLE, speed FLOAT, create_time TIMESTAMP, vdop FLOAT, road_id INT, road_name nchar ( 80 ), update_time TIMESTAMP, accuracy FLOAT, card_id nchar ( 80 ), in_grid_flag INT, imei nchar ( 80 ), cell_code nchar ( 80 ), gps_count nchar ( 20 ) ) TAGS ( patrol_tag INT );

create database iotpro vgroups 8 CACHEMODEL 'both';
create table iotpro.iot_equip_data (time timestamp,data_value double,receive_time timestamp,alarm_flag tinyint,is_noise tinyint,value_type_id int,forewarn_model_id int,detail nchar(200)) tags (equip_id bigint, field_id bigint, field_code nchar(100), equip_type_id int, city_code nchar(50),district_code nchar(50),street_code nchar(50),community_code nchar(50), project_id int, manufacturer_id int);